// Copyright 2026 RareBird Games. All Rights Reserved.

#include "BPPinSerializer.h"
#include "BPTypeDescriptor.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraph/EdGraphNode.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"

TSharedPtr<FJsonObject> FBPPinSerializer::Serialize(const UEdGraphPin* Pin)
{
    TSharedPtr<FJsonObject> O = MakeShared<FJsonObject>();
    if (!Pin) return O;

    // The identity tuple. A pin name repeats across directions on one node
    // (a Knot's InputPin and OutputPin are the mild case), so PinId is what
    // identifies a pin and the name is what reads it. Both are reported.
    O->SetStringField(TEXT("pin_id"), Pin->PinId.ToString());
    O->SetStringField(TEXT("pin_name"), Pin->PinName.ToString());
    O->SetStringField(TEXT("pin_direction"),
        Pin->Direction == EGPD_Input ? TEXT("Input") : TEXT("Output"));
    O->SetObjectField(TEXT("type"), FBPTypeDescriptor::ToJson(Pin->PinType));

    // All three default slots, not only the string one. An object pin holds
    // its value in DefaultObject and an FText pin in DefaultTextValue, so a
    // reader that looks at DefaultValue alone reports every asset reference
    // and every text literal in a graph as empty.
    O->SetStringField(TEXT("default_value"), Pin->DefaultValue);
    O->SetStringField(TEXT("default_object"),
        Pin->DefaultObject != nullptr ? Pin->DefaultObject->GetPathName() : FString());
    O->SetStringField(TEXT("default_text"), Pin->DefaultTextValue.ToString());
    // What the node gave the pin itself. A default equal to this one was
    // authored by nobody, which is the difference between reporting a graph
    // and reporting its schema.
    O->SetStringField(TEXT("autogenerated_default_value"), Pin->AutogeneratedDefaultValue);

    O->SetBoolField(TEXT("is_hidden"), Pin->bHidden != 0);
    O->SetBoolField(TEXT("is_orphaned"), Pin->bOrphanedPin != 0);

    // Sorted by the far end's identity rather than left in link order, which
    // an edit can permute without changing what the graph means.
    using FSortedLink = TPair<FString, TSharedPtr<FJsonValue>>;
    TArray<FSortedLink> Links;
    for (UEdGraphPin* Linked : Pin->LinkedTo)
    {
        UEdGraphNode* Owner = Linked != nullptr ? Linked->GetOwningNodeUnchecked() : nullptr;
        if (Owner == nullptr) continue;
        const FString NodeGuid = Owner->NodeGuid.ToString();
        const FString PinId = Linked->PinId.ToString();
        TSharedPtr<FJsonObject> L = MakeShared<FJsonObject>();
        L->SetStringField(TEXT("node_guid"), NodeGuid);
        L->SetStringField(TEXT("pin_id"), PinId);
        L->SetStringField(TEXT("pin_name"), Linked->PinName.ToString());
        Links.Emplace(NodeGuid + PinId, MakeShared<FJsonValueObject>(L));
    }
    Links.Sort([](const FSortedLink& A, const FSortedLink& B) { return A.Key < B.Key; });

    TArray<TSharedPtr<FJsonValue>> LinkValues;
    LinkValues.Reserve(Links.Num());
    for (const FSortedLink& Link : Links) { LinkValues.Add(Link.Value); }
    O->SetArrayField(TEXT("links"), LinkValues);
    return O;
}
